app:
  name: miporfolio
  image:
    repository: jorgeas/astroporfolio
    tag: "a4a1326aa7d478accd9f39efe65d279b841191ea"
    pullPolicy: Always

# Variables para los recursos del clúster
replicaCount: 1


service:
  port: 80
  targetPort: 80

ingress:
  host: www.jorgedesarrollador.com