app:
  name: miporfolio
  image:
    repository: jorgeas/astroporfolio
    tag: "304690471e1111b29a348483e5113655e39fceb5"
    pullPolicy: Always

# Variables para los recursos del clúster
replicaCount: 1


service:
  port: 80
  targetPort: 80

ingress:
  host: www.jorgedesarrollador.com