app:
  name: miporfolio
  image:
    repository: jorgeas/astroporfolio
    tag: "59ec38494d612f995bf2955e21fcc7e135e5f350"
    pullPolicy: Always

# Variables para los recursos del clúster
replicaCount: 1


service:
  port: 80
  targetPort: 80

ingress:
  host: www.jorgedesarrollador.com