apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: jenkins
  annotations:
    kubernetes.io/ingress.class: "public"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: public
  tls:
  - hosts:
    - jenkins.jorgedesarrollador.com
    secretName: jenkins-tls-prod
  rules:
  - host: jenkins.jorgedesarrollador.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins 
            port:
              number: 8080