pipeline {
  agent {
    kubernetes {
      yaml """
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: kaniko
            image: gcr.io/kaniko-project/executor:debug
            command:
            - /busybox/cat
            tty: true
            volumeMounts:
              - name: docker-config
                mountPath: /kaniko/.docker
          volumes:
            - name: docker-config
              secret:
                secretName: dockerhub-secret
                items:
                  - key: .dockerconfigjson
                    path: config.json
        """
    }
  }

  environment {
    DOCKER_IMAGE = "jorgeas/astroporfolio:latest" 
    HELM_REPO_URL = "https://github.com/JorgeAsca/PorfolioAstro.git"
  }

  stages {
    stage('Checkout & Skip Check') {
      steps {
        checkout scm
        script {
            // Obtenemos el mensaje del último commit
            def commitMsg = sh(script: 'git log -1 --pretty=%B', returnStdout: true).trim()
            echo "Mensaje del último commit: ${commitMsg}"
            
            // Si el mensaje contiene [skip ci], abortamos la ejecución con éxito
            if (commitMsg.contains("[skip ci]")) {
                echo "Detectado commit automático. Saltando ejecución para evitar bucle."
                currentBuild.result = 'SUCCESS'
                error("Deteniendo pipeline: Commit de Jenkins detectado.")
            }
        }
      }
    }

    stage('Build & Push Image') {
      steps {
        container('kaniko') {
          sh """
          /kaniko/executor \
            --context /home/jenkins/agent/workspace/pipeline/Astroporfolio \
            --dockerfile Astroporfolio/deploy/build_img/Dockerfile \
            --destination jorgeas/astroporfolio:${GIT_COMMIT} \
            --destination jorgeas/astroporfolio:latest \
            --snapshot-mode=redo \
            --single-snapshot
          """
        }
      }
    }

    stage('Update Helm Values') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'git-creds', 
          usernameVariable: 'GIT_USER',
          passwordVariable: 'GIT_PASSWORD'
        )]) {
          sh """
          git config user.email "jenkins@ci.com"
          git config user.name "jenkins"
          
          sed -i "s/tag:.*/tag: \\"${GIT_COMMIT}\\"/" Astroporfolio/deploy/miporfolio/values.yaml
          
          git add Astroporfolio/deploy/miporfolio/values.yaml
          
          # Mensaje reforzado para que el primer stage lo detecte siempre
          git commit -m "chore: update image tag ${GIT_COMMIT} [skip ci]"
          
          git push https://${GIT_USER}:${GIT_PASSWORD}@github.com/JorgeAsca/PorfolioAstro.git HEAD:main
          """
        }
      }
    }
  }
}